[package]
name = "recipe_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json", "msgpack"]}

sqlite = "0.30.1"

dotenvy = "0.15"



